In [ ]:
print("Dear Learners !! Let us learn Numpy")


Dear Learners !! Let us learn Numpy


In [ ]:
distance = [11,25,38,49]
time = [0.24,37,40,58]
speed = distance/time
print(speed)

TypeError: unsupported operand type(s) for /: 'list' and 'list'

In [ ]:
#Create numpy from the list
import numpy as np
np_distance = np.array(distance)
np_time = np.array(time)
np_speed = np_distance/np_time
print(np_speed)

NameError: name 'distance' is not defined

NUMPY

In [ ]:
#Create numpy from 2D list
list2 = [[1,2,3],[4,5,6],[7,8,9]]
print(list2)
np_list2 = np.array(list2)
print(np_list2)
print(type(list2))
print(type(np_list2))

[[1, 2, 3], [4, 5, 6], [7, 8, 9]]
[[1 2 3]
 [4 5 6]
 [7 8 9]]
<class 'list'>
<class 'numpy.ndarray'>


In [ ]:
#Create 1D array
arr1 = np.array([7,10,16,16,18,20])
print(arr1)
print(type(arr1))

[ 7 10 16 16 18 20]
<class 'numpy.ndarray'>


In [ ]:
print(arr1.ndim)
print(arr1.shape)
print(arr1.size)
print(arr1.dtype)

1
(6,)
6
int32


In [ ]:
#Create 2D array
arr2 = np.array([[9,2,3],[3,9,3]])
print(arr2)
print(type(arr2)

[[9 2 3]
 [3 9 3]]
<class 'numpy.ndarray'>


2

In [ ]:
#Attributes of array
print(arr2.ndim)
print(arr2.shape)
print(arr2.size)
print(arr2.dtype)

2
(2, 3)
6
int32


In [ ]:
#Create 2D array
arr3 = np.array([[[9,2,3],[3,9,3],[8,2,5]], [[5,6,7],[2,6,7],[7,3,5]]])
print(arr3)
print(type(arr3))


[[[9 2 3]
  [3 9 3]
  [8 2 5]]

 [[5 6 7]
  [2 6 7]
  [7 3 5]]]
<class 'numpy.ndarray'>


In [ ]:
#Attributes of array
print(arr3.ndim)
print(arr3.shape)
print(arr3.size)
print(arr3.dtype)
print(arr3.itemsize)

3
(2, 3, 3)
18
int32
4


In [3]:
#using arange
import numpy as np
n1 = np.arange(10)
print(n1)
n2 = np.arange(2,11)
print(n2)
n3 = np.arange(2,21,2)
print(n3)

[0 1 2 3 4 5 6 7 8 9]
[ 2  3  4  5  6  7  8  9 10]
[ 2  4  6  8 10 12 14 16 18 20]


In [4]:
#using linspace
l1 = np.linspace(1,15,20)
l1
l2 = np.linspace(1,15,100)
l2

array([ 1.        ,  1.14141414,  1.28282828,  1.42424242,  1.56565657,
        1.70707071,  1.84848485,  1.98989899,  2.13131313,  2.27272727,
        2.41414141,  2.55555556,  2.6969697 ,  2.83838384,  2.97979798,
        3.12121212,  3.26262626,  3.4040404 ,  3.54545455,  3.68686869,
        3.82828283,  3.96969697,  4.11111111,  4.25252525,  4.39393939,
        4.53535354,  4.67676768,  4.81818182,  4.95959596,  5.1010101 ,
        5.24242424,  5.38383838,  5.52525253,  5.66666667,  5.80808081,
        5.94949495,  6.09090909,  6.23232323,  6.37373737,  6.51515152,
        6.65656566,  6.7979798 ,  6.93939394,  7.08080808,  7.22222222,
        7.36363636,  7.50505051,  7.64646465,  7.78787879,  7.92929293,
        8.07070707,  8.21212121,  8.35353535,  8.49494949,  8.63636364,
        8.77777778,  8.91919192,  9.06060606,  9.2020202 ,  9.34343434,
        9.48484848,  9.62626263,  9.76767677,  9.90909091, 10.05050505,
       10.19191919, 10.33333333, 10.47474747, 10.61616162, 10.75

In [5]:
#using random
r1 = np.random.rand(3,4)
print(r1)
r2 = np.random.rand(3,5)
print(r2)
r2.ndim

[[0.1269983  0.45255114 0.57033786 0.55823222]
 [0.75616452 0.46274643 0.85601868 0.21743653]
 [0.64028414 0.43504497 0.49769737 0.02353224]]
[[0.24872564 0.56306759 0.79053421 0.48241235 0.49699607]
 [0.38842096 0.62186638 0.92665993 0.64858884 0.01590648]
 [0.48517121 0.51136064 0.92064626 0.52055213 0.46106217]]


2

In [ ]:
# Create numpy with specific number: Using full(sizeofarray, number)
s1 = np.full((3,4),5)
s1

array([[5, 5, 5, 5],
       [5, 5, 5, 5],
       [5, 5, 5, 5]])

In [ ]:
z = np.zeros(10)
print(z)
z1 = np.zeros((4,5))
print(z1)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]


In [6]:
o = np.ones(10)
print(o)
o1 = np.zeros((4,5))
print(o1)

[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]


In [7]:
o1 = o1 +5
print(o1)

[[5. 5. 5. 5. 5.]
 [5. 5. 5. 5. 5.]
 [5. 5. 5. 5. 5.]
 [5. 5. 5. 5. 5.]]


In [9]:
e = np.eye(100)
print(e)
print(e.ndim)
print(e.shape)

[[1. 0. 0. ... 0. 0. 0.]
 [0. 1. 0. ... 0. 0. 0.]
 [0. 0. 1. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 1. 0. 0.]
 [0. 0. 0. ... 0. 1. 0.]
 [0. 0. 0. ... 0. 0. 1.]]
2
(100, 100)


In [10]:
# accessing array elements using indexing
array1 = np.array([[10,20,30,40,50],[12,13,17,21,33]])
print ("1st row elements of array 1 :", array1[0])
print ("2nd row elements of array 1 :", array1[1])
print("1st column elements of array 1:", array1[:,1])
print("1st and 2nd column elements of array 1:", array1[:,0:2])
print("1st to 4th column elements of an array 1:", array1[:,:4])
print("2nd row elements of array1 ", array1[1,1:3])

1st row elements of array 1 : [10 20 30 40 50]
2nd row elements of array 1 : [12 13 17 21 33]
1st column elements of array 1: [20 13]
1st and 2nd column elements of array 1: [[10 20]
 [12 13]]
1st to 4th column elements of an array 1: [[10 20 30 40]
 [12 13 17 21]]
2nd row elements of array1  [13 17]


In [11]:
array1 = np.array([[10,20,30,40,50],[12,13,17,21,33]])

In [12]:
arr = [2,3,4,65]
print(arr)
print(arr[3])
print(arr[1:3])
print(arr[0:3])

[2, 3, 4, 65]
65
[3, 4]
[2, 3, 4]


In [13]:
arr = np.array([[10,20,30,40,50],[12,13,17,21,33]])
arr[1,:]

array([12, 13, 17, 21, 33])

In [15]:
ap = np.arange(1,21)
print(ap)
print(ap.shape)
print(ap.reshape(10,2))
print(ap)

[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20]
(20,)
[[ 1  2]
 [ 3  4]
 [ 5  6]
 [ 7  8]
 [ 9 10]
 [11 12]
 [13 14]
 [15 16]
 [17 18]
 [19 20]]
[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20]


In [16]:
an = np.random.rand(3,4)
print(an)
print(an.resize(4,3))
print(an)

[[8.42582022e-01 5.59826853e-01 6.21718649e-04 5.68691171e-01]
 [8.29290049e-01 4.65235194e-01 7.15225256e-01 1.11750134e-01]
 [6.69594436e-02 8.95384224e-01 1.01630880e-01 1.38885851e-01]]
None
[[8.42582022e-01 5.59826853e-01 6.21718649e-04]
 [5.68691171e-01 8.29290049e-01 4.65235194e-01]
 [7.15225256e-01 1.11750134e-01 6.69594436e-02]
 [8.95384224e-01 1.01630880e-01 1.38885851e-01]]


In [17]:
# Arithmetic Operations
a1 = np.arange(1,11)
a2 = np.arange(11,21)
print(a1)
print(a2)
print("Addition:", (a1+a2))
print("Subtraction:", (a1-a2))
print("Multiplication:", (a1*5))
print("Division:", (a1/a2))
print("Power:", (a1**2))

[ 1  2  3  4  5  6  7  8  9 10]
[11 12 13 14 15 16 17 18 19 20]
Addition: [12 14 16 18 20 22 24 26 28 30]
Subtraction: [-10 -10 -10 -10 -10 -10 -10 -10 -10 -10]
Multiplication: [ 5 10 15 20 25 30 35 40 45 50]
Division: [0.09090909 0.16666667 0.23076923 0.28571429 0.33333333 0.375
 0.41176471 0.44444444 0.47368421 0.5       ]
Power: [  1   4   9  16  25  36  49  64  81 100]


In [ ]:
arr = np.array([[2,61,20,39],[49,38,10,71]])
score = arr>25
print(score)
print(arr[score])
print(type(score))
print(type(arr[score]))


[[False  True False  True]
 [ True  True False  True]]
[61 39 49 38 71]
<class 'numpy.ndarray'>
<class 'numpy.ndarray'>


(2, 4)

In [18]:
agg = np.arange(11)
print(agg)
print(np.max(agg))
print(np.min(agg))
print(np.sum(agg))
print(len(agg))
print(np.sqrt(agg))
print(np.std(agg))
print(np.mean(agg))
print(np.median(agg))
print(np.cos(agg))
print(np.sin(agg))
print(np.tan(agg))

[ 0  1  2  3  4  5  6  7  8  9 10]
10
0
55
11
[0.         1.         1.41421356 1.73205081 2.         2.23606798
 2.44948974 2.64575131 2.82842712 3.         3.16227766]
3.1622776601683795
5.0
5.0
[ 1.          0.54030231 -0.41614684 -0.9899925  -0.65364362  0.28366219
  0.96017029  0.75390225 -0.14550003 -0.91113026 -0.83907153]
[ 0.          0.84147098  0.90929743  0.14112001 -0.7568025  -0.95892427
 -0.2794155   0.6569866   0.98935825  0.41211849 -0.54402111]
[ 0.          1.55740772 -2.18503986 -0.14254654  1.15782128 -3.38051501
 -0.29100619  0.87144798 -6.79971146 -0.45231566  0.64836083]


In [19]:
#Axis: (1 for row, 0 for column)
ax1 = np.array([[2,4,6,8],[3,1,6,2],[4,7,2,6]])
print(ax1)
print("Sum:",np.sum(ax1))
print("Column-wise Sum:",np.sum(ax1,axis =0))
print("Row-wise Sum:",np.sum(ax1,axis =1))

[[2 4 6 8]
 [3 1 6 2]
 [4 7 2 6]]
Sum: 51
Column-wise Sum: [ 9 12 14 16]
Row-wise Sum: [20 12 19]


In [20]:
ax1 = np.array([[2,4,6,8],[3,1,6,2],[4,7,2,6]])
np.sum(ax1)
np.sum(ax1,axis=1)
np.sum(ax1,axis=0)

array([ 9, 12, 14, 16])

In [21]:
s1 = np.array([[2,4,6,8],[3,1,6,2],[4,7,2,6]])
s2 = np.array([[1,4,2,6],[4,1,5,3],[1,2,5,9]])
print(s1)
print("Next Array")
print(s2)
print(np.hstack((s1,s2)))
print(np.vstack((s2,s1)))


[[2 4 6 8]
 [3 1 6 2]
 [4 7 2 6]]
Next Array
[[1 4 2 6]
 [4 1 5 3]
 [1 2 5 9]]
[[2 4 6 8 1 4 2 6]
 [3 1 6 2 4 1 5 3]
 [4 7 2 6 1 2 5 9]]
[[1 4 2 6]
 [4 1 5 3]
 [1 2 5 9]
 [2 4 6 8]
 [3 1 6 2]
 [4 7 2 6]]


In [22]:
#To create a flattened array
arr5 = np.array([[3,4,8],[10,29,19]])
print(arr5)
print(arr5.ndim)
arr1 = arr5.ravel()
print(arr1)
print(arr1.ndim)

[[ 3  4  8]
 [10 29 19]]
2
[ 3  4  8 10 29 19]
1


In [23]:
#Reshape - Changes the shape of 1D to 2D, does not affect the original array
print(arr1)
print(arr1.reshape(2,3)) # does not change the original array
#arr1 = arr1.reshape(2,3)  - changes the original array
print(arr1)

[ 3  4  8 10 29 19]
[[ 3  4  8]
 [10 29 19]]
[ 3  4  8 10 29 19]


In [24]:
#Resize - Changes the shape of 1D to 2D, changes the original array

print(arr1)
arr1.resize(2,3)
print(arr1)

[ 3  4  8 10 29 19]
[[ 3  4  8]
 [10 29 19]]


In [26]:
x=np.arange(1,50,1)

#1. Sine :
print(np.sin(x))
#2. Cosine:
print(np.cos(x))
#3. tan :
print(np.tan(x))
#4. Exp func -
print(np.exp(x))
#5. Log func - log x -log10:
print(np.log10(x))

[ 0.84147098  0.90929743  0.14112001 -0.7568025  -0.95892427 -0.2794155
  0.6569866   0.98935825  0.41211849 -0.54402111 -0.99999021 -0.53657292
  0.42016704  0.99060736  0.65028784 -0.28790332 -0.96139749 -0.75098725
  0.14987721  0.91294525  0.83665564 -0.00885131 -0.8462204  -0.90557836
 -0.13235175  0.76255845  0.95637593  0.27090579 -0.66363388 -0.98803162
 -0.40403765  0.55142668  0.99991186  0.52908269 -0.42818267 -0.99177885
 -0.64353813  0.29636858  0.96379539  0.74511316 -0.15862267 -0.91652155
 -0.83177474  0.01770193  0.85090352  0.90178835  0.12357312 -0.76825466
 -0.95375265]
[ 0.54030231 -0.41614684 -0.9899925  -0.65364362  0.28366219  0.96017029
  0.75390225 -0.14550003 -0.91113026 -0.83907153  0.0044257   0.84385396
  0.90744678  0.13673722 -0.75968791 -0.95765948 -0.27516334  0.66031671
  0.98870462  0.40808206 -0.54772926 -0.99996083 -0.53283302  0.42417901
  0.99120281  0.64691932 -0.29213881 -0.96260587 -0.74805753  0.15425145
  0.91474236  0.83422336 -0.01327675 -

In [ ]:
array = np.arange(0,10)
print(array)
array.reshape(2,5)

In [ ]:
array.max()

In [ ]:
array.min()

In [ ]:
x=np.arange(1,50,1)
x
np.log10(x)

array([0.        , 0.30103   , 0.47712125, 0.60205999, 0.69897   ,
       0.77815125, 0.84509804, 0.90308999, 0.95424251, 1.        ,
       1.04139269, 1.07918125, 1.11394335, 1.14612804, 1.17609126,
       1.20411998, 1.23044892, 1.25527251, 1.2787536 , 1.30103   ,
       1.32221929, 1.34242268, 1.36172784, 1.38021124, 1.39794001,
       1.41497335, 1.43136376, 1.44715803, 1.462398  , 1.47712125,
       1.49136169, 1.50514998, 1.51851394, 1.53147892, 1.54406804,
       1.5563025 , 1.56820172, 1.5797836 , 1.59106461, 1.60205999,
       1.61278386, 1.62324929, 1.63346846, 1.64345268, 1.65321251,
       1.66275783, 1.67209786, 1.68124124, 1.69019608])

In [ ]:
a = 1
b = 0
c = a/b

ZeroDivisionError: division by zero

In [ ]:
array1 = np.arange(0,11)
print(array1)
print(array1/array1)

[ 0  1  2  3  4  5  6  7  8  9 10]
[nan  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.]


C:\Users\1613287\AppData\Local\Continuum\Anaconda3\lib\site-packages\ipykernel_launcher.py:3: RuntimeWarning: invalid value encountered in true_divide
  This is separate from the ipykernel package so we can avoid doing imports until


In [ ]:
#Array with Arrays
import numpy as np
array1 = np.arange(0,11)
print("array 1 :", array1)
array2 = np.arange(0,11)
print ("array 2 :", array2)
arraysum = array1 + array2
print ("array Sum :", arraysum)
arraydiff = array1 - array2
print("array difference", arraydiff)
arraymul = array1 * array2
print("array multiplication", arraymul)

In [ ]:
#Array Scalar Operations
array1
print ("array 1 :", array1)
print ("arra1 + 10 :", array1 + 10)
print ("array1 - 10 : ", array1 - 10)
print ("array1 ** 2 :", array1 **2)


In [ ]:
#Numpy Functions
print("Square root :", np.sqrt(array1))
print("Max value of array1 :", np.max(array1))
print("Min value of array1 :", np.min(array1))
print("sin value of the array 1", np.sin(array1))
print("cosine value of the array 1", np.cos(array1))

Numpy Functions
refer to the inline documentation related to the numpy universal functions, there are 1000s of built in functions for numpy https://docs.scipy.org/doc/numpy/reference/ufuncs.html